package com.myspace.fsi_client_onboarding;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public customer() {
    }




}